<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Daths-PC" ignored="0" name="Test(failed)" tests="2" failures="1" timestamp="05 Sep 2018 03:10:51 GMT" time="44.765" errors="0">
  <testcase name="login2" time="0.623" classname="script.LoginTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.fail(Assert.java:95)
at script.LoginTest.login2(LoginTest.java:28)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- login2 -->
  <testcase name="login1" time="0.552" classname="script.LoginTest"/>
</testsuite> <!-- Test(failed) -->
